### ISSUE TITLE
Missing existing county information

### ISSUE THREAD

**Issue by idess1** [project-rakan/rakan#3]
Provided index files are missing the existing county information for every precinct.

- **A redesign of the index file is needed.**
- **No redesign of** `Reader.h` **or** `Reader.cc` **is necessary,** but further methods and re-computing file offsets are needed to accommodate for added information.

To mitigate missing information, current scoring function for existing county similarity is 0 for every step taken by `MetropolisHastings()`. Expect the scores to be less accurate.

**Comment by kdmcc** [comment]
The engine wrapper will be initialized with the county information, and create the precinct nodes with the information
