### ISSUE TITLE
Docker build command failing

### ISSUE THREAD

**Issue by SarvagyaGupta** [project-rakan/rakan#31]
Docker version 19.03.9, build 9d98839

When running the `docker build . -t rakan`, I get the following error:
- ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: no such file or directory 
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Can you help resolve this issue?

**Comment by qwergram** [comment]
You are not running the docker daemon. Double click the docker executable that is installed on your computer. On windows, the app is called "Docker Desktop" I imagine the mac has a similarly named executable.

**Comment by SarvagyaGupta** [comment]
Can I get instructions to run it?

**Comment by SarvagyaGupta** [comment]
I did `brew install docker` to install it onto my machine. I don't have an app to double click on

**Comment by qwergram** [comment]
Does this question help with launching docker? 

https://apple.stackexchange.com/a/373914

**Comment by SarvagyaGupta** [comment]
Got it to work. I would suggest putting these steps in the developer docs:
1. Download docker app
2. Follow steps in the docker to start a container
3. Execute `docker build . -t rakan` to build the backend

Or something like the ^
