### ISSUE TITLE
Cannot open iowa.idx in test folder

### ISSUE THREAD

**Issue by idess1** [project-rakan/rakan#5]
Calling `fopen()` on the iowa index file returns `nullptr` in the test folder. However, calling `fopen()` on the same file in the src folder does not return a `nullptr`. Note,

- Paths have been checked in both cases and are correct.
- `#include <stdio.h>` exists in both cases.
- Checks have been made to guarantee `fopen()` does not return a `nullptr` in the src folder, and `rakan_run` runs successfully, so no, it is not a fluke.

As a consequence, all tests in `test_reader.cc` are failing due to a `nullptr` error. Tests have been commented out for the meantime so that the `test_suite` is not blocked due to a segmentation fault.

**Comment by qwergram** [comment]
Closing, as we'll be utilizing a new file IO methodology
